// Package jsonrpc implements a robust JSON-RPC 2.0 runtime for LSP.
//
// Invariants:
//  1. Unknown JSON fields are silently preserved (forward-compatible).
//  2. Unknown method names are accepted and routed to a fallback handler.
//  3. Request IDs are always preserved — never generated by the library for requests.
//  4. No panic path exists in any public function.
//  5. Messages are value types; no shared mutable state.
package jsonrpc

import (
	"encoding/json"
	"fmt"
)

const (
	Version = "2.0"

	// Standard error codes
	ParseError     = -32700
	InvalidRequest = -32600
	MethodNotFound = -32601
	InvalidParams  = -32602
	InternalError  = -32603

	// LSP-specific error codes
	RequestCancelled = -32800
	ContentModified  = -32801
	RequestFailed    = -32803
)

// RequestID is a JSON-RPC request identifier (string or number).
// In JSON-RPC 2.0, id can be a string, number, or null.
type RequestID struct {
	Str    string
	Num    int64
	IsStr  bool
	IsNull bool
}

// MarshalJSON implements json.Marshaler.
func (id RequestID) MarshalJSON() ([]byte, error) {
	if id.IsNull {
		return []byte("null"), nil
	}
	if id.IsStr {
		return json.Marshal(id.Str)
	}
	return json.Marshal(id.Num)
}

// UnmarshalJSON implements json.Unmarshaler.
func (id *RequestID) UnmarshalJSON(data []byte) error {
	id.IsNull = false
	id.IsStr = false
	if string(data) == "null" {
		id.IsNull = true
		return nil
	}
	// Try number first.
	var n json.Number
	if err := json.Unmarshal(data, &n); err == nil {
		i, err := n.Int64()
		if err == nil {
			id.Num = i
			return nil
		}
	}
	// Try string.
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		id.Str = s
		id.IsStr = true
		return nil
	}
	return fmt.Errorf("jsonrpc: invalid request id: %s", string(data))
}

// Equals reports whether two RequestIDs are equal.
func (id RequestID) Equals(other RequestID) bool {
	if id.IsNull != other.IsNull {
		return false
	}
	if id.IsNull {
		return true
	}
	if id.IsStr != other.IsStr {
		return false
	}
	if id.IsStr {
		return id.Str == other.Str
	}
	return id.Num == other.Num
}

// Message is a JSON-RPC 2.0 message — either request, response, or notification.
// This is the wire-format representation.
type Message struct {
	// JSONRPC is always "2.0".
	JSONRPC string `json:"jsonrpc"`

	// ID is non-nil for requests and responses.
	// Null for notifications.
	ID *RequestID `json:"id,omitempty"`

	// Method is set for requests and notifications.
	Method string `json:"method,omitempty"`

	// Params is the request/notification parameters (raw JSON).
	Params json.RawMessage `json:"params,omitempty"`

	// Result is set on successful responses.
	Result json.RawMessage `json:"result,omitempty"`

	// Error is set on error responses.
	Error *ResponseError `json:"error,omitempty"`

	// methodPresent records that the wire form carried a method field at
	// all, which an empty Method cannot express. Set by every
	// constructor that names a method, and by UnmarshalJSON.
	methodPresent bool
}

// UnmarshalJSON records whether the wire form carried a method field. The
// decoder cannot tell an absent field from an empty one once both land in
// one string, and the three message kinds hinge on that difference.
func (m *Message) UnmarshalJSON(data []byte) error {
	type alias Message
	var shadow alias
	if err := json.Unmarshal(data, &shadow); err != nil {
		return err
	}
	var probe struct {
		Method *json.RawMessage `json:"method"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return err
	}
	*m = Message(shadow)
	m.methodPresent = probe.Method != nil
	return nil
}

// IsRequest returns true if this message is a request (has ID and Method).
func (m *Message) IsRequest() bool {
	return m.ID != nil && m.methodPresent
}

// IsNotification returns true if this message is a notification (has Method, no ID).
func (m *Message) IsNotification() bool {
	return m.ID == nil && m.methodPresent
}

// IsResponse returns true if this is a response (has ID, no method field).
//
// methodPresent, not Method alone, is what separates a response from a
// malformed request: {"id":1,"result":{...}} omits method entirely, while
// {"id":1,"method":""} carries it but leaves the name empty. Both decode
// to an empty Method. Deciding by the field alone classified the second as a
// response, and server.Run drops responses, so that request was discarded in
// silence and the client waited forever. JSON-RPC 2.0 wants one terminal
// outcome per request, and a name that resolves to nothing gets
// MethodNotFound.
func (m *Message) IsResponse() bool {
	return m.ID != nil && !m.methodPresent
}

// IsError returns true if this is an error response.
func (m *Message) IsError() bool {
	return m.IsResponse() && m.Error != nil
}

// ResponseError represents a JSON-RPC 2.0 error object.
type ResponseError struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

func (e *ResponseError) Error() string {
	return fmt.Sprintf("jsonrpc error %d: %s", e.Code, e.Message)
}

// NewRequest creates a request message.
func NewRequest(id RequestID, method string, params json.RawMessage) *Message {
	return &Message{
		JSONRPC:       Version,
		ID:            &id,
		Method:        method,
		methodPresent: true,
		Params:        params,
	}
}

// NewNotification creates a notification message.
func NewNotification(method string, params json.RawMessage) *Message {
	return &Message{
		JSONRPC:       Version,
		Method:        method,
		methodPresent: true,
		Params:        params,
	}
}

// NewResponse creates a successful response message.
func NewResponse(id RequestID, result json.RawMessage) *Message {
	return &Message{
		JSONRPC: Version,
		ID:      &id,
		Result:  result,
	}
}

// NewErrorResponse creates an error response message.
func NewErrorResponse(id RequestID, code int, message string, data json.RawMessage) *Message {
	return &Message{
		JSONRPC: Version,
		ID:      &id,
		Error: &ResponseError{
			Code:    code,
			Message: message,
			Data:    data,
		},
	}
}
