package conformance

import (
	"fmt"
	"slices"
	"sort"
	"strings"
)

// GenerateDocs renders docs/conformance.md from the registry so the document
// can never drift from what the scorecard actually checks.
func GenerateDocs() string {
	var b strings.Builder
	b.WriteString(`# Conformance Map — goal.md Part Y → Executing Tests

> GENERATED by internal/conformance (registry.go). Do not hand-edit:
> ` + "`go test ./test/conformance -run TestGenerateDocs`" + ` fails on drift.
> Regenerate via OMNISP_UPDATE_CONFORMANCE=1.
>
> Scoring: AUTO probe passing = 1.0, PARTIAL = 0.5, GATE = existence in fast
> mode / executed in full, DEFERRED = tracked in its own milestone domain
> below with an independent denominator.

`)
	domains := map[string][]*Check{}
	for i := range Registry.Checks {
		c := &Registry.Checks[i]
		domains[c.Domain] = append(domains[c.Domain], c)
	}

	order := []string{"core", "x5", "x7", "x8", "x9"}
	seenDomains := make(map[string]struct{}, len(order))
	for _, dom := range order {
		seenDomains[dom] = struct{}{}
	}
	var extraDomains []string
	for dom := range domains {
		if _, seen := seenDomains[dom]; !seen {
			extraDomains = append(extraDomains, dom)
		}
	}
	sort.Strings(extraDomains)
	order = append(order, extraDomains...)
	for _, dom := range order {
		checks := domains[dom]
		if len(checks) == 0 {
			continue
		}
		if dom == "core" {
			b.WriteString("## Core domain (gated)\n\n")
		} else {
			b.WriteString(fmt.Sprintf("## Deferred domain %s (independent denominator)\n\n", strings.ToUpper(dom)))
		}
		cats := map[string][]*Check{}
		var catOrder []string
		for _, c := range checks {
			if _, seen := cats[c.Category]; !seen {
				catOrder = append(catOrder, c.Category)
			}
			cats[c.Category] = append(cats[c.Category], c)
		}
		sort.Strings(catOrder)
		for _, cat := range catOrder {
			fmt.Fprintf(&b, "### %s\n\n| ID | Item | Clause | Tests / Gate | Status |\n|---|---|---|---|---|\n", cat)
			for _, c := range cats[cat] {
				ref := ""
				switch {
				case c.Probe != nil:
					var syms []string
					for _, g := range c.Probe.Groups {
						for _, t := range g.Tests {
							syms = append(syms, "`"+t+"`")
						}
					}
					ref = strings.Join(syms, ", ")
				case c.Gate != nil:
					ref = "`" + c.Gate.Cmd + "`"
				default:
					ref = "—"
				}
				status := string(c.Status)
				if c.Milestone != "" {
					status += "→" + c.Milestone
				} else if c.Reason != "" && c.Status == StatusPartial {
					status = "PARTIAL (" + c.Reason + ")"
				}
				text := strings.ReplaceAll(c.Text, "|", "\\|")
				fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", c.ID, text, c.Clause, ref, status)
			}
			b.WriteString("\n")
		}
	}
	b.WriteString("## Score dimensions\n\n")
	b.WriteString(coreWeightsSummary())
	b.WriteString("Deferred domains are scored independently and never merge into the core gate.\n")
	return b.String()
}

// coreWeightsSummary renders the core weighting straight from coreWeights plus
// the categories that actually appear under Domain:"core". Hardcoding the list
// was a silent-lie risk: adding an eighth weighted category would leave the
// generated page claiming the old seven, and TestGenerateDocs would stay green.
// Deriving it makes this page the guard for its own accounting.
func coreWeightsSummary() string {
	var weighted, unweighted []string
	counts := map[string]int{}
	for _, c := range Registry.Checks {
		if c.Domain != "core" {
			continue
		}
		counts[c.Category]++
		if _, ok := coreWeights[c.Category]; ok {
			continue
		}
		if !slices.Contains(unweighted, c.Category) {
			unweighted = append(unweighted, c.Category)
		}
	}
	sort.Strings(unweighted)

	cats := make([]string, 0, len(coreWeights))
	for cat := range coreWeights {
		cats = append(cats, cat)
	}
	sort.Strings(cats)
	for _, cat := range cats {
		weighted = append(weighted, fmt.Sprintf("%s %g", cat, coreWeights[cat]))
	}

	out := "Core weights: " + strings.Join(weighted, " · ") + ".\n"
	if len(unweighted) > 0 {
		parts := make([]string, 0, len(unweighted))
		for _, cat := range unweighted {
			parts = append(parts, fmt.Sprintf("%s (%d)", cat, counts[cat]))
		}
		out += fmt.Sprintf("Core-domain categories carrying no weight (display only, excluded from the gate denominator): %s.\n",
			strings.Join(parts, ", "))
	}
	return out
}
