package conformance

// Registry is the single source of truth for the conformance scorecard.
// docs/conformance.md is GENERATED from this table (W2-E); hand edits there
// drift and fail TestGenerateDocs.
//
// Package paths were verified against the tree at closeout; a moved test
// must update its Check here in the same commit.
var Registry = struct{ Checks []Check }{
	Checks: []Check{
		// ---------- Y0 Correctness ----------
		{ID: "Y0-1", Domain: "core", Category: "Y0", Clause: "INV-SNAPSHOT-002", Weight: 1,
			Text: "Every request captures exactly one Snapshot", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestINV_SNAPSHOT_002_HoverServesCapturedSnapshot"}}, {Pkg: "internal/workspace/snapshot", Tests: []string{"TestSnapshotIsolation"}}}}},
		{ID: "Y0-2", Domain: "core", Category: "Y0", Clause: "PROT-SYNC-001", Weight: 1,
			Text: "Incremental edits are never state-dropped", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestP1_RapidEditsOrderedUnderConcurrency", "TestPROT_SYNC_001_SequentialRangeEditsLossless"}}}}},
		{ID: "Y0-3", Domain: "core", Category: "Y0", Clause: "INV-POS-001", Weight: 1,
			Text: "Position conversion is property-tested", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/workspace/position", Tests: []string{"TestRoundTripProperty", "TestCJKCharacters"}}}}},
		{ID: "Y0-4", Domain: "core", Category: "Y0", Clause: "§E0/E7/nested", Weight: 1,
			Text: "Build context participates in semantic identity", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/nested", Tests: []string{"TestE_NestedBuildContextID"}}, {Pkg: "internal/languages/golang", Tests: []string{"TestE0_BackendBuildContextID"}}}}},
		{ID: "Y0-5", Domain: "core", Category: "Y0", Clause: "§D11", Weight: 1,
			Text: "Stale results cannot publish", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestD11_RenameContentModifiedOnAgedSnapshot"}}}}},
		{ID: "Y0-6", Domain: "core", Category: "Y0", Clause: "SEM-SAFE-001", Weight: 1,
			Text: "Rename never falls back to textual replacement", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestSEM_SAFE_001_RenameFailsClosed"}}}}},
		{ID: "Y0-7", Domain: "core", Category: "Y0", Clause: "§C9/§I12", Weight: 1,
			Text: "Workspace edits are preflight validated (fail-closed rename gates)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/ccls", Tests: []string{"TestX3_RenameFailClosedWithoutCompileDb"}}}}},
		{ID: "Y0-8", Domain: "core", Category: "Y0", Clause: "§E6/H2/X3", Weight: 1,
			Text: "Ambiguous build contexts fail closed for S3; macro advisory surfaced", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/ccls", Tests: []string{"TestX3_HeaderAmbiguitySurfaced", "TestX3_MacroSuspectSurfaced"}}}}},
		{ID: "Y0-9", Domain: "core", Category: "Y0", Clause: "§D12/§I12", Weight: 1,
			Text: "Generated/source-map gaps block unsafe edits", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/workspace/virtual", Tests: []string{"TestD12_UnmappedGeneratedBlocksEdit"}},
				{Pkg: "internal/runtime/server", Tests: []string{"TestSrcmapGate_RenameBlockedByUnmappedGenerated"}}}}},
		{ID: "Y0-10", Domain: "core", Category: "Y0", Clause: "INV-BACKEND-001", Weight: 1,
			Text: "Backend restart invalidates old-epoch results", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/nested", Tests: []string{"TestG2_CrashFailsPendingFastAndRestarts", "TestG2_RepeatedCrashesQuarantine"}}}}},

		// ---------- Y1 Stability ----------
		{ID: "Y1-1", Domain: "core", Category: "Y1", Clause: "§F5/F6/C1", Weight: 1,
			Text: "Queues bounded", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/scheduler", Tests: []string{"TestSchedulerAdmissionRejection"}}}}},
		{ID: "Y1-2", Domain: "core", Category: "Y1", Clause: "K0 cache bounds", Weight: 1,
			Text: "Caches bounded (pkgCache FIFO-evicted at 64 entries, persistent index disk-budgeted)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/languages/golang", Tests: []string{"TestK0_PackageCacheHits"}},
				{Pkg: "internal/index/persistent", Tests: []string{"TestBudget_RejectsWhenFull"}}}}},
		{ID: "Y1-3", Domain: "core", Category: "Y1", Clause: "§F15/S13", Weight: 1,
			Text: "Goroutines owned", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestS13_HalfFrameDisconnect"}}}}},
		{ID: "Y1-4", Domain: "core", Category: "Y1", Clause: "§C7/F10/G7", Weight: 1,
			Text: "Cancellation propagates end-to-end", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/nested", Tests: []string{"TestSendRequest_TimeoutAndCancel"}}}}},
		{ID: "Y1-5", Domain: "core", Category: "Y1", Clause: "§G2", Weight: 1,
			Text: "Backend crash isolated", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/supervisor", Tests: []string{"TestMarkDegraded", "TestQuarantineAfterMaxCrashes"}}}}},
		{ID: "Y1-6", Domain: "core", Category: "Y1", Clause: "IDX-TXN-004/L8", Weight: 1,
			Text: "Index corruption isolated", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/persistent", Tests: []string{"TestL7_ChecksumMismatchQuarantines", "TestL6_TXN003_IdempotentRecovery"}}}}},
		{ID: "Y1-7", Domain: "core", Category: "Y1", Clause: "L17", Weight: 1,
			Text: "Disk budget refusal preserves last good generation", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/persistent", Tests: []string{"TestBudget_RejectsWhenFull", "TestL4_CrashBeforePublishKeepsOldGeneration"}}}}},
		{ID: "Y1-8", Domain: "core", Category: "Y1", Clause: "§F16", Weight: 1,
			Text: "Panic boundary tested", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestINV_ARCH_001_ServerResilience"}}, {Pkg: "internal/transport/httpserver", Tests: []string{"TestRoutingErrors"}}}}},
		{ID: "Y1-9", Domain: "core", Category: "Y1", Clause: "§S14/F17", Weight: 1,
			Text: "Race detector clean across all packages", Status: StatusGate,
			Gate: &Gate{Cmd: "go test -race -count=1 -timeout 900s ./...", TargetPkg: "internal/runtime/server", TargetTest: "TestS13_HalfFrameDisconnect"}},
		{ID: "Y1-10", Domain: "core", Category: "Y1", Clause: "§S16", Weight: 1,
			Text: "Soak has no monotonic resource leak", Status: StatusGate,
			Gate: &Gate{Cmd: "go test -tags soak -count=1 -timeout 300s ./test/soak/", TargetPkg: "test/soak", TargetTest: "TestSoak_SustainedMixedLoadBounded"}},

		// ---------- Y2 Compatibility ----------
		{ID: "Y2-1", Domain: "core", Category: "Y2", Clause: "§S10/Y2", Weight: 1,
			Text: "LSP 3.17 baseline passes (golden scenarios frozen)", Status: StatusGate,
			Gate: &Gate{Cmd: "go test -count=1 ./test/golden/", TargetPkg: "test/golden", TargetTest: "TestGoldenScenarios"}},
		{ID: "Y2-2", Domain: "core", Category: "Y2", Clause: "§A7/Y2", Weight: 1,
			Text: "Unknown future methods/notifications tolerated; params field-level tolerance tested; LSP 3.18 feature gating deferred (DEF-A7GATE)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/protocol/jsonrpc", Tests: []string{"TestUnknownNotificationSilentlyIgnored", "TestMalformedJSONDoesNotPanic", "TestY2_UnknownParamsFieldsTolerated"}}}}},
		{ID: "Y2-3", Domain: "core", Category: "Y2", Clause: "§C4", Weight: 1,
			Text: "Position encoding negotiation tested", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/workspace/position", Tests: []string{"TestCJKCharacters", "TestEmojiEncoding"}}}}},
		{ID: "Y1-11", Domain: "core", Category: "Y1", Clause: "F13/F14 memory budget", Weight: 1,
			Text: "Memory budgets enforced (global soft/hard + per-backend quotas)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/budget", Tests: []string{"TestF13_SoftLimitWarnsHardLimitRefuses", "TestF14_PerBackendQuotaIsolated"}}}}},
		{ID: "UX-C11", Domain: "core", Category: "UX", Clause: "C11/I17/I18 diagnostics pipeline", Weight: 1,
			Text: "Push debounced + pull handler + stable resultId over six-field cache key", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestC11_PushDebouncedPublish", "TestC11_PullStableResultIdAndCache"}}}}},
		{ID: "UX-C4", Domain: "core", Category: "UX", Clause: "C4 position encoding negotiation", Weight: 1,
			Text: "initialize negotiates encoding; negotiated value reaches backend requests", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestC4_PositionEncodingNegotiation"}}}}},
		{ID: "UX-I19", Domain: "core", Category: "UX", Clause: "I19 code actions three-class safety", Weight: 1,
			Text: "codeAction serves in-range diagnostics; no disguised executable commands", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI19_CodeActionInRangeOnly"}}}}},
		{ID: "WS-D14", Domain: "core", Category: "WORKSPACE", Clause: "D14 file watcher (polling)", Weight: 1,
			Text: "Zero-dependency poller detects create/modify/delete; vendored dirs ignored", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/workspace/watch", Tests: []string{"TestWatcherDetectsCreateModifyDelete", "TestWatcherIgnoresVendoredAndBaselineSilence"}}}}},
		{ID: "AC-I12", Domain: "core", Category: "ACC", Clause: "I12 cross-file edit-set preflight", Weight: 1,
			Text: "Overlapping same-file edits refused; boundary-touching accepted", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI12_ValidateEditSet"}}}}},
		{ID: "T-S3IDX", Domain: "core", Category: "TESTING", Clause: "S3 fuzz targets: index decode + freshness seal", Weight: 1,
			Text: "Hostile store manifests and sealed payloads never panic recovery paths", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/persistent", Tests: []string{"FuzzOpenSnapshotCorruptStore", "FuzzFreshnessSealVerify"}}}}},
		{ID: "T-R7FLAG", Domain: "core", Category: "CONFIG", Clause: "R7 feature flags registry", Weight: 1,
			Text: "Unknown/expired flags rejected at validation with known-name listing", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/config", Tests: []string{"TestR7_FeatureFlagValidation"}}}}},
		{ID: "T-O5VER", Domain: "core", Category: "PLUGIN", Clause: "O5 plugin API version range", Weight: 1,
			Text: "apiVersion negotiates against a supported range, not a single constant", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestO5_APIVersionRangeNegotiation"}}}}},
		{ID: "T-S9SEQ", Domain: "core", Category: "TESTING", Clause: "S9 end-to-end edit-sequence goldens", Weight: 1,
			Text: "Four multi-step session scenarios frozen as golden frames", Status: StatusGate,
			Gate: &Gate{Cmd: "go test -count=1 ./test/golden/", TargetPkg: "test/golden"}},
		{ID: "UX-C8", Domain: "core", Category: "UX", Clause: "C8 work-done progress", Weight: 1,
			Text: "$/progress begin/end reported for token-bearing long queries", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestC8_ProgressNotifications"}}}}},
		{ID: "UX-I9", Domain: "core", Category: "UX", Clause: "I9 completion incompleteness", Weight: 1,
			Text: "Heuristic completion declared IsIncomplete for client re-query", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI9_CompletionIsIncompleteNegotiation"}}}}},
		{ID: "UX-Q2", Domain: "core", Category: "UX", Clause: "Q2 error projection", Weight: 1,
			Text: "Failed queries project supervisor recovery guidance to clients", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestQ2_ErrorProjectionCarriesSupervisorGuidance"}}}}},
		{ID: "ST-G5WD", Domain: "core", Category: "STAB", Clause: "G5 hung worker watchdog", Weight: 1,
			Text: "Silent workers with in-flight requests recycled via HungGrace watchdog", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/nested", Tests: []string{"TestG5_WatchdogRestartsSilentWorkerWithInflight", "TestG5_WatchdogSparesIdleWorker"}}}}},
		{ID: "AC-I11c", Domain: "core", Category: "ACC", Clause: "I11 rename collisions", Weight: 1,
			Text: "Rename onto bound names refused fail-closed with decisive report", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/golang", Tests: []string{"TestRenameCollisionDetection"}}}}},
		{ID: "J-WIRE", Domain: "core", Category: "MEMO", Clause: "J engine production wiring", Weight: 1,
			Text: "Semantic reads memoized by revision; transient failures retryable; bounded table (K0)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/runtime/server", Tests: []string{"TestJ_EngineMemoizesSemanticReads"}},
				{Pkg: "internal/semantic/query", Tests: []string{"TestK0_QueryMemoBounded"}}}}},
		{ID: "Y2-6a", Domain: "core", Category: "Y2", Clause: "I16/I20/I22 feature negotiation", Weight: 1,
			Text: "Optional capabilities negotiated (signatureHelp/formatting/inlayHint)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/runtime/server", Tests: []string{"TestI16_SignatureHelpNegotiatedAndUnsupported", "TestI20_FormattingFullDocumentEdit"}},
				{Pkg: "internal/languages/golang", Tests: []string{"TestFeatures_GolangBridgeSyntaxTier"}}}}},
		{ID: "Y2-4", Domain: "core", Category: "Y2", Clause: "C9 workspace edits", Weight: 1,
			Text: "WorkspaceEdit capability differences tested (documentChanges negotiation + legacy form)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestY24_WorkspaceEditCapabilityMatrix"}}}}},
		{ID: "Y2-5", Domain: "core", Category: "Y2", Clause: "S11/X8 client matrix", Weight: 1,
			Text: "Client compatibility matrix current (VS Code/Neovim/Emacs/Helix/Zed)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestX8_ClientDocsPresent"}}}}},
		{ID: "Y2-6", Domain: "core", Category: "Y2", Clause: "A7/§C14", Weight: 1,
			Text: "MCP revision pinned", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/protocol/mcp", Tests: []string{"TestInitializePinsProtocolRevision", "TestToolsListIsFiveReadOnly"}}}}},
		{ID: "Y2-7", Domain: "core", Category: "Y2", Clause: "R4/W2/P8/P9", Weight: 1,
			Text: "Public API schemas versioned", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "cmd/omnilsp", Tests: []string{"TestRenderJSON"}}}}},

		// ---------- Y3 Security ----------
		{ID: "Y3-1", Domain: "core", Category: "Y3", Clause: "N1/N2/N3 trust gates", Weight: 1,
			Text: "Trust gates enforced (workspace states Untrusted/Restricted/Trusted + plugin default-deny)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/trust", Tests: []string{"TestN1_DefaultUntrusted", "TestN3_UntrustedBlocksExecution", "TestN1_RestrictedWhitelist"}},
				{Pkg: "internal/languages/nested", Tests: []string{"TestN3_UntrustedWorkspaceBlocksBackendStart"}},
				{Pkg: "internal/plugin", Tests: []string{"TestO2_DefaultDeny"}}}}},
		{ID: "Y3-2", Domain: "core", Category: "Y3", Clause: "SEC-EXEC-001/§N4", Weight: 1,
			Text: "No shell execution of compile database commands", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/security", Tests: []string{"TestSEC_N7_SymlinkEscapeContained"}}}}},
		{ID: "Y3-3", Domain: "core", Category: "Y3", Clause: "§N7/S23", Weight: 1,
			Text: "Symlink escape contained; path traversal rejected", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/security", Tests: []string{"TestSEC_N7_SymlinkEscapeContained", "TestSEC_N7_PathTraversalRejected"}}}}},
		{ID: "Y3-4", Domain: "core", Category: "Y3", Clause: "§N11/S23", Weight: 1,
			Text: "Secrets redacted in logs/errors", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/security", Tests: []string{"TestSEC_N11_RedactionAudit"}}}}},
		{ID: "Y3-5", Domain: "core", Category: "Y3", Clause: "§N8", Weight: 1,
			Text: "Remote non-loopback endpoint rejected (v1 fail-closed)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/transport/httpserver", Tests: []string{"TestValidateAddr"}}}}},
		{ID: "Y3-6", Domain: "core", Category: "Y3", Clause: "OPS-PRIV-001/§N12/P3", Weight: 1,
			Text: "Telemetry source-free by default; cardinality bounded", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/telemetry", Tests: []string{"TestCounterName", "TestTraceIDPropagation"}}}}},
		{ID: "Y3-7", Domain: "core", Category: "Y3", Clause: "N13/W0/P10 repro bundle", Weight: 1,
			Text: "Repro bundle privacy modes tested (metadata/redacted/full-source)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "cmd/omnilsp", Tests: []string{"TestN13_DefaultModeIsRedacted", "TestN13_FullSourceRequiresExplicitOptIn", "TestN13_NoSecretsInBundle"}}}}},
		{ID: "Y3-8", Domain: "core", Category: "Y3", Clause: "O2/N14 least privilege", Weight: 1,
			Text: "Plugin capabilities least-privilege (default deny)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestO2_DefaultDeny", "TestO3_ManifestValidation"}}}}},
		{ID: "Y3-9", Domain: "core", Category: "Y3", Clause: "N15/X8 supply chain", Weight: 1,
			Text: "Supply-chain artifacts generated (CycloneDX SBOM from go.sum)", Status: StatusGate,
			Gate: &Gate{Cmd: "go run scripts/gen-sbom.go -o sbom.cdx.json .", TargetPkg: "cmd/omnilsp"}},

		// ---------- Y4 Observability ----------
		{ID: "Y4-1", Domain: "core", Category: "Y4", Clause: "§P0/P1/I25", Weight: 1,
			Text: "Request -> Snapshot -> Query -> Backend traceable", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI25_ExplainReportsEvidenceChain"}}, {Pkg: "internal/telemetry", Tests: []string{"TestTraceIDPropagation"}}}}},
		{ID: "Y4-2", Domain: "core", Category: "Y4", Clause: "§G3/App-D", Weight: 1,
			Text: "Backend health visible", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/supervisor", Tests: []string{"TestMarkDegraded", "TestQuarantineAfterMaxCrashes"}}}}},
		{ID: "Y4-3", Domain: "core", Category: "Y4", Clause: "§F6", Weight: 1,
			Text: "Queue saturation visible", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/scheduler", Tests: []string{"TestSchedulerStats"}}}}},
		{ID: "Y4-4", Domain: "core", Category: "Y4", Clause: "§K0", Weight: 1,
			Text: "Cache hit/miss visible", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/golang", Tests: []string{"TestK_StatusCacheCounters", "TestK0_PackageCacheHits"}}}}},
		{ID: "Y4-5", Domain: "core", Category: "Y4", Clause: "§P3", Weight: 1,
			Text: "Metrics cardinality bounded", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/telemetry", Tests: []string{"TestCounterName"}}}}},
		{ID: "Y4-6", Domain: "core", Category: "Y4", Clause: "§I25", Weight: 1,
			Text: "Explain API reports evidence/fallback", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI25_ExplainReportsEvidenceChain"}}}}},
		{ID: "Y4-7", Domain: "core", Category: "Y4", Clause: "§P8", Weight: 1,
			Text: "Doctor identifies environment faults (dual output)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "cmd/omnilsp", Tests: []string{"TestRenderText", "TestRenderJSON"}}}}},

		// ---------- Y5 Maintainability ----------
		{ID: "Y5-1", Domain: "core", Category: "Y5", Clause: "§U2", Weight: 1,
			Text: "Core packages document invariants", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestU2_InvariantHeadersPresent"}}}}},
		{ID: "Y5-2", Domain: "core", Category: "Y5", Clause: "INV-ARCH-002/§U1", Weight: 1,
			Text: "No protocol imports in Semantic Core", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestARCH002_NoProtocolImportsInCore"}}}}},
		{ID: "Y5-3", Domain: "core", Category: "Y5", Clause: "§U9", Weight: 1,
			Text: "ADRs exist for major architecture choices", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "cmd/omnilsp", Tests: []string{"TestADRFilesExist"}}}}},
		{ID: "Y5-4", Domain: "core", Category: "Y5", Clause: "U4/C17 protocol manifest", Weight: 1,
			Text: "Protocol surface reproducible (canonical manifest drift check; hand-written-by-design)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestY54_ProtocolManifestFresh"}}}}},
		{ID: "Y5-5", Domain: "core", Category: "Y5", Clause: "§U5", Weight: 1,
			Text: "Dependencies justified and whitelisted (x/tools for Go bridge semantic load)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestU5_NoThirdPartyRuntimeDeps"}}}}},
		{ID: "Y5-6", Domain: "core", Category: "Y5", Clause: "R4/R5", Weight: 1,
			Text: "Version surfaces documented (docs/versions.md) and wire types fingerprint-frozen", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestY54_ProtocolManifestFresh"}}}}},
		{ID: "Y5-7", Domain: "core", Category: "Y5", Clause: "§V6/V7", Weight: 1,
			Text: "Conformance map generated from registry (no doc drift)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/conformance", Tests: []string{"TestGenerateDocs"}}}}},

		// ---------- PERF (S17/S18) ----------
		{ID: "PERF-S19", Domain: "core", Category: "PERF", Clause: "S19 large queries", Weight: 1,
			Text: "Large-query throughput scaling + cancelability measured", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/perf", Tests: []string{"TestS19_ReferencesScalingCurve"}}}}},
		{ID: "PERF-S20", Domain: "core", Category: "PERF", Clause: "S20 accuracy KPI", Weight: 1,
			Text: "Accuracy KPI formulas canonical and NaN-safe", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/telemetry", Tests: []string{"TestS20_KPIFormulas", "TestS20_KPIZeroDenominatorSafe"}}}}},
		{ID: "PERF-1", Domain: "core", Category: "PERF", Clause: "§S17", Weight: 1,
			Text: "Benchmark reports carry mandatory metadata banner", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/perf", Tests: []string{"TestS17_MetadataPresent"}}}}},
		{ID: "PERF-2", Domain: "core", Category: "PERF", Clause: "§S18", Weight: 1,
			Text: "Interactive SLO targets met (hot hover/definition/completion/syntax-update P50+P95)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/perf", Tests: []string{"TestS18_InteractiveSLO"}}}}},
		{ID: "PERF-3", Domain: "core", Category: "PERF", Clause: "§S21", Weight: 1,
			Text: "Qualified corpus zero-error goals (six-bucket classification all-zero)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/corpus", Tests: []string{"TestS21_ZeroErrorClassification"}}}}},
		{ID: "PERF-4", Domain: "core", Category: "PERF", Clause: "§S22", Weight: 1,
			Text: "Metamorphic invariance (whitespace / line endings / comment injection)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "test/corpus", Tests: []string{"TestS22_MetamorphicWhitespaceInvariance", "TestS22_MetamorphicLineEndingInvariance", "TestS22_MetamorphicCommentInjectionInvariance"}}}}},

		// ---------- Deferred domain x5 (persistent intelligence) ----------
		{ID: "X5-1", Domain: "x5", Category: "INDEX", Clause: "T5/L4-L8 persistent index", Weight: 1,
			Text: "Persistent index with transactional integrity (atomic publish/quarantine/recovery)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/persistent", Tests: []string{"TestL4_CrashBeforePublishKeepsOldGeneration", "TestL6_TXN002_HalfWrittenSegmentNotDiscoverable", "TestCompact_ReducesSegmentsAndPreservesReads"}}}}},
		{ID: "X5-2", Domain: "x5", Category: "INTEROP", Clause: "L14/L15 interop adapters", Weight: 1,
			Text: "SCIP+LSIF import/export adapters (provenance preserved)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/interop", Tests: []string{"TestL14_SCIPRoundTrip", "TestL15_LSIFRoundTrip", "TestImportProvenanceMarked"}}}}},
		{ID: "X5-3", Domain: "x5", Category: "QUERY", Clause: "J0-J8 query engine", Weight: 1,
			Text: "Incremental query engine (Key/six-state/singleflight/cycle/freshness gate)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/semantic/query", Tests: []string{"TestJ4_StateTransitions", "TestJ6_SingleflightIndependentCancel", "TestJ5_SelfWaitDetected", "TestJ7_StalePublishRejected"}}}}},
		{ID: "X5-5", Domain: "x5", Category: "CACHE", Clause: "K3/K4 cache policy", Weight: 1,
			Text: "Negative caching bounded + loaded-data identity checks (K3/K4)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{
				{Pkg: "internal/semantic/query", Tests: []string{"TestK3_NegativeCachingPolicy"}},
				{Pkg: "internal/index/persistent", Tests: []string{"TestL9_FutureSchemaQuarantinesAndFallsBack"}}}}},
		{ID: "X5-6", Domain: "x5", Category: "INDEX", Clause: "L9/L10 migration+freshness", Weight: 1,
			Text: "Schema forward-compat reader + freshness tuple gates visibility", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/persistent", Tests: []string{"TestL9_FutureSchemaQuarantinesAndFallsBack", "TestL10_FreshnessTupleGatesVisibility"}}}}},
		{ID: "X5-4", Domain: "x5", Category: "GRAPH", Clause: "M0-M4 dependency graph", Weight: 1,
			Text: "Dependency graph with selective invalidation + fingerprints + generator edges", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/index/graph", Tests: []string{"TestM1_SelectivePropagation", "TestM2_FingerprintSkip", "TestM3_FanoutSafetyValve", "TestM4_GeneratorInvalidation"}}}}},

		// ---------- Deferred domain x7 (plugin platform) ----------
		{ID: "X7-1", Domain: "x7", Category: "PLUGIN", Clause: "O0-O5 plugin platform", Weight: 1,
			Text: "Out-of-process plugins: discovery/validation/capability gates/lifecycle", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestO3_ManifestValidation", "TestO4_QuarantineAfterCrashLoop", "TestExecutor_LaunchHandshake"}}}}},
		{ID: "X7-2", Domain: "x7", Category: "TRUST", Clause: "N14 hostile input", Weight: 1,
			Text: "Hostile manifests rejected (checksum/path traversal/API drift)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestN14_ChecksumMismatchRejected", "TestN14_HostileEntrypointRejected"}}}}},

		// ---------- Deferred domain x8 (distribution) ----------
		{ID: "X8-1", Domain: "x8", Category: "DIST", Clause: "W3-W8 packaging", Weight: 1,
			Text: "Multi-platform build matrix + SBOM + sha256 attestations", Status: StatusGate,
			Gate: &Gate{Cmd: "bash scripts/build-multiplatform.sh dev dist-smoke", TargetPkg: "cmd/omnilsp"}},
		{ID: "X8-3", Domain: "x8", Category: "APISEC", Clause: "X6/C15 read API security", Weight: 1,
			Text: "HTTP read API auth gate + per-source rate limiting", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/transport/httpserver", Tests: []string{"TestX6_BearerTokenGate", "TestX6_PerSourceRateLimitBucket"}}}}},
		{ID: "DEF-E2E3", Domain: "post-x9", Category: "BUILDCTX", Clause: "E2/E3 multi-context per file", Weight: 1,
			Text: "Multiple BuildContexts per document + active-context selection entry points", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "single derived context covers current backends; selection UI/API lands with the index service (X10)"},
		{ID: "DEF-JAVA", Domain: "post-x9", Category: "LANGS", Clause: "E11/H6 Java backend (Tier S)", Weight: 1,
			Text: "jdtls nested bridge with classpath/project model", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "bridge pattern is templated; jdtls project model needs a dedicated integration round — see docs/language-packs.md"},
		{ID: "DEF-TIERA", Domain: "post-x9", Category: "LANGS", Clause: "H7 Tier A languages", Weight: 1,
			Text: "Kotlin/C#/Lua/Bash/CMake/Proto bridges", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "H7 admits languages only with a written plan; none has one yet — admission gate working as designed"},
		{ID: "DEF-DATA", Domain: "post-x9", Category: "LANGS", Clause: "H8 data/config/markup", Weight: 1,
			Text: "JSON/YAML/TOML/XML/Dockerfile semantic support", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "schema-driven tier requires a tree-sitter or schema-store decision first"},
		{ID: "DEF-NOTEBOOK", Domain: "post-x9", Category: "WORKSPACE", Clause: "D13 notebook LSP sync", Weight: 1,
			Text: "notebookDocument/* synchronization over the existing cell model", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "data model shipped (workspace/virtual/notebook.go); wire protocol waits for a client that needs it"},
		{ID: "DEF-HIER", Domain: "post-x9", Category: "SEMANTIC", Clause: "I23 call/type hierarchies", Weight: 1,
			Text: "prepareCallHierarchy/incoming/outgoing + type hierarchy handlers", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "depends on cross-file reference edges (G9 phase 2 index service); syntax-tier stub would be fake completeness (V9)"},
		{ID: "DEF-SANDBOX", Domain: "post-x9", Category: "SECURITY", Clause: "N6 OS process sandbox", Weight: 1,
			Text: "rlimit/job-object/env-allowlist around backend and plugin processes", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "trust gates (§N1-N3) + path containment (§N7) cover v1 threat model; OS sandbox is defense-in-depth"},
		{ID: "DEF-TRACEEXP", Domain: "post-x9", Category: "OBSERVABILITY", Clause: "P1/P5 trace export + sampling", Weight: 1,
			Text: "structured span-tree export format and sampling-rate configuration", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "TraceIDs, explain ring and replay JSONL satisfy correlation today; OTLP-grade export waits for an ops consumer"},
		{ID: "DEF-PLUGMOUNT", Domain: "post-x9", Category: "PLUGIN", Clause: "O2 capability-to-API mounting", Weight: 1,
			Text: "plugin-declared capabilities gate runtime API mount points", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "manifest validation + trust-gated launch are live; server-side plugin API surface itself is X10 scope"},
		{ID: "DEF-REMOTEIDX", Domain: "post-x9", Category: "INDEX", Clause: "L12/L13 remote index", Weight: 1,
			Text: "remote index fetch with availability degradation", Status: StatusDeferred,
			Milestone: "X10", Reason: "OPTIONAL scale feature; local persistent store is complete and self-sufficient"},
		{ID: "DEF-W7UPD", Domain: "post-x9", Category: "DISTRIBUTION", Clause: "W7 self-update checks", Weight: 1,
			Text: "update availability command/check", Status: StatusDeferred,
			Milestone: "X10", Reason: "OPTIONAL; package-manager distributions handle updates externally"},
		{ID: "UX-I21TOK", Domain: "core", Category: "UX", Clause: "I21/C10 semantic tokens wire contract", Weight: 1,
			Text: "Legend shared with emitters; flat data-array wire shape; no false incremental claim", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestI21_LegendMatchesEmittedTypes", "TestHandleSemanticTokens"}}}}},
		{ID: "C3-CAPS", Domain: "core", Category: "UX", Clause: "C3 capability/handler bidirectional alignment", Weight: 1,
			Text: "Every declared provider has a handler; every served feature is declared", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestC3_CapabilitiesDeclaredEqualsServed"}}}}},
		{ID: "C12-META", Domain: "core", Category: "UX", Clause: "C12/B5 resultMeta + queryTrace exits", Weight: 1,
			Text: "Envelope metadata (status/completeness/evidence) and engine counters exposed via custom methods", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestC12_ResultMetaAndQueryTrace"}}}}},
		{ID: "T2-DECL", Domain: "core", Category: "Y2", Clause: "T2/I14 declaration served via optional capability", Weight: 1,
			Text: "textDocument/declaration declared and served through DeclarationProvider (ADR-0009 D2)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/runtime/server", Tests: []string{"TestT2_DeclarationServedAndDeclared"}}}}},
		{ID: "O2-EXECGATE", Domain: "x7", Category: "PLUGIN", Clause: "O2/O4 plugin executor gates and crash containment", Weight: 1,
			Text: "Pre-spawn validate+capability gates refuse without a child; handshake grants are exactly manifest∩grant; OnExit fires once and feeds quarantine", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestLaunch_RejectsBeforeSpawn", "TestLaunch_HandshakeGrantsFiltered", "TestOnExit_OnceAndCrashQuarantine"}}}}},
		{ID: "O3-DISCOVER", Domain: "x7", Category: "PLUGIN", Clause: "O3 discovery scan semantics", Weight: 1,
			Text: "Only manifest dirs discovered; broken manifests surfaced per-entry without aborting; deterministic order", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/plugin", Tests: []string{"TestDiscover_ScansAndToleratesBroken"}}}}},
		{ID: "B6-SIGHON", Domain: "core", Category: "UX", Clause: "B6 signature completeness honesty", Weight: 1,
			Text: "Syntax-layer signature results carry IncompleteKnownSubset, not zero-value Complete", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/languages/golang", Tests: []string{"TestFeatures_GolangBridgeSyntaxTier"}}}}},
		{ID: "DEF-A7GATE", Domain: "post-x9", Category: "COMPATIBILITY", Clause: "A7 LSP 3.18 feature gating", Weight: 1,
			Text: "Per-feature version gate mechanism for 3.18+ additions", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "baseline pinned at 3.17 with fingerprint freeze; no 3.18 feature is consumed yet, so the gate has nothing to gate"},
		{ID: "DEF-P2METRICS", Domain: "post-x9", Category: "OBSERVABILITY", Clause: "P2 full metrics set + Recorder wiring", Weight: 1,
			Text: "~20 missing counters (latency/cancelled/quarantine/cache/index) and production telemetry.Recorder activation", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "six core counters + explain ring cover v1 ops; full set lands with the trace-export workstream (DEF-TRACEEXP)"},
		{ID: "DEF-APPEREQ", Domain: "post-x9", Category: "OBSERVABILITY", Clause: "Appendix E request state machine stages", Weight: 1,
			Text: "Decoded→Admitted→SnapshotCaptured→Queued→Running→Validating stage observability", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "terminal states are observable via response projection; stage spans need the P1 span-tree format first"},
		{ID: "DEF-INVNAMES", Domain: "post-x9", Category: "TESTING", Clause: "Appendix A invariant test naming", Weight: 1,
			Text: "INV-ARCH-003/OPS-PRIV-001 dedicated tests; rename 5 covered-but-unnamed tests to carry INV IDs", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "all 12 invariants have at least indirect coverage; dedicated names are audit ergonomics, not correctness"},
		{ID: "DEF-I5GRAPH", Domain: "post-x9", Category: "INDEX", Clause: "I5 cross-language reference graph", Weight: 1,
			Text: "Cross-language symbol graph (Go<->TS etc.) over the persistent index", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "single-language backends ship first; graph needs the persistent index wired into the live path (see DEF-E2E3)"},
		{ID: "DEF-CCLSDIAG", Domain: "post-x9", Category: "LANGUAGE-PACKS", Clause: "T3/I17 ccls diagnostics forwarding", Weight: 1,
			Text: "Forward clangd publishDiagnostics notifications from the nested bridge to clients", Status: StatusDeferred,
			Milestone: "X3", Reason: "nested readLoop currently drops server->client notifications; forwarding needs a notification tap mechanism"},
		{ID: "DEF-COMPRESOLVE", Domain: "post-x9", Category: "UX", Clause: "I13 completionItem/resolve", Weight: 1,
			Text: "Lazy resolution of completion detail/documentation via completionItem/resolve", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "items carry Detail/Documentation inline today; resolve pays off only with expensive per-item computation"},
		{ID: "DEF-S15MIXED", Domain: "post-x9", Category: "TESTING", Clause: "S15 mixed-workload stress", Weight: 1,
			Text: "Concurrent completion/hover/definition stress with backend-restart injection and tail-latency tracking", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "soak covers mixed load partially; restart-injection e2e needs the X3 harness"},
		{ID: "DEF-TENANT", Domain: "post-x9", Category: "SECURITY", Clause: "N10/S23 cross-tenant cache isolation tests", Weight: 1,
			Text: "Tests proving cache keys cannot leak across tenants/build contexts", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "multi-tenancy itself is deferred (DEF-DATA); content-hash keys already isolate builds"},
		{ID: "DEF-X3LARGE", Domain: "post-x9", Category: "TESTING", Clause: "X3 large-repository index tests", Weight: 1,
			Text: "Index performance/correctness tests against a real large repository corpus", Status: StatusDeferred,
			Milestone: "X3", Reason: "needs a vendored large repo fixture; synthetic corpora cover unit scale"},
		{ID: "DEF-EDITORS", Domain: "post-x9", Category: "GOVERNANCE", Clause: "X2/S11 editor compatibility matrix", Weight: 1,
			Text: "Live VS Code/Neovim interop verification runs recorded as evidence", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "docs + golden sequences exist; live editor sessions need a human/CI-GUI loop"},
		{ID: "DEF-E6CTX", Domain: "post-x9", Category: "LANGUAGE-PACKS", Clause: "E6 build-context field completeness", Weight: 1,
			Text: "standard/target/sysroot/includes fields in BuildContextID for C/C++", Status: StatusDeferred,
			Milestone: "X3", Reason: "compile_commands parser lands first; version+workdir hash is honest for v1"},
		{ID: "DEF-IDXWIRE", Domain: "post-x9", Category: "INDEX", Clause: "C12 indexStats/reindex live wiring", Weight: 1,
			Text: "omnilsp/indexStats and omnilsp/reindex once the persistent index joins the live path", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "index is offline-tooling today (X5 registry); reindex additionally needs N4 trust gating"},
		{ID: "DEF-POLICYDOCS", Domain: "post-x9", Category: "GOVERNANCE", Clause: "A6/A8/G9 policy documentation pages", Weight: 1,
			Text: "Operating modes, Go toolchain floor policy, bootstrap language strategy as standalone docs", Status: StatusDeferred,
			Milestone: "post-X9", Reason: "policies exist in code comments and ADR fragments; consolidation page is editorial work"},
		{ID: "DEF-COMPACT", Domain: "post-x9", Category: "INDEX", Clause: "L16 compaction scheduling", Weight: 1,
			Text: "background-triggered generation compaction", Status: StatusDeferred,
			Milestone: "X10", Reason: "Compact() verified in tests; production scheduling attaches when the persistent store enters the live server path (index service)"},
		{ID: "X6-C15GRPC", Domain: "post-x8", Category: "GRPC", Clause: "C15 gRPC v1", Weight: 1,
			Text: "gRPC v1 projection of the read API", Status: StatusDeferred,
			Milestone: "post-X8", Reason: "HTTP covers the read-API semantics; gRPC is a duplicate surface deferred until a consumer requires it"},
		{ID: "X8-2", Domain: "x8", Category: "CLIENTS", Clause: "S11/X8 client profiles", Weight: 1,
			Text: "Full client compatibility matrix (VS Code/Neovim/Emacs/Helix/Zed)", Status: StatusAuto,
			Probe: &Probe{Groups: []ProbeGroup{{Pkg: "internal/conformance", Tests: []string{"TestX8_ClientDocsPresent"}}}}},

		// ---------- Deferred domain x9 (hardening release duty) ----------
		{ID: "X9-1", Domain: "x9", Category: "RELEASE", Clause: "T7/S6 release duty", Weight: 1,
			Text: "Sustained soak + differential mismatch triage pipeline", Status: StatusPartial,
			Milestone: "x9", Reason: "triage pipeline live (test/corpus/triage.go) + nightly workflow (.github/workflows/nightly.yml); the 55m/24h sustained runs execute in CI"},
		{ID: "X9-2", Domain: "x9", Category: "RELEASE", Clause: "C17/U4 reproducibility", Weight: 1,
			Text: "Protocol reproducibility check (manifest fingerprint; -check mode in CI form)", Status: StatusPartial,
			Milestone: "x9+", Reason: "fingerprint check live (scripts/gen-protocol.go -check); metamodel-driven codegen stays post-X9+"},
	},
}
